BaSP-TG-73: Super admin redux implementation
BaSP-m2022/diego-trackgenix-app pull request #36
Opened 2022-06-14 17:26 UTC by IvanHGo

Worked on this branch: @IvanHGo @Agustin-Chazarreta
In the first commit you can see we started the problematic implementing the redux setup and creating the methods following the weekly class.
Later we notice that the problematic needed diferents states for each action so I added them in the following commits.
When the methods GET, PUT, POST and DELETE were finished I corriged some issues and moved them to the thunks file for better funcionality. 
For more information or errors, let me know.

2022-06-16 15:59 UTC, cellamarematias requested changes

2022-06-16 15:59 UTC, cellamarematias commented on src/Components/SuperAdmins/index.jsx
> +    fetch(`${process.env.REACT_APP_API_URL}/super-admins/${ids}`)
Hi! You must remove this fetch from the index to the thunks.

2022-06-16 15:59 UTC, cellamarematias commented on src/Components/SuperAdmins/index.jsx
> +  const isLoading = useSelector((state) => state.superAdmins.isLoading);
I would add   `const` error= useSelector((state) => state.superAdmins.error);` So you can handle the error.

2022-06-17 02:57 UTC, IvanHGo commented on src/Components/SuperAdmins/index.jsx
> +    fetch(`${process.env.REACT_APP_API_URL}/super-admins/${ids}`)
Hi! Thanks Mati, I realized that I didn't need that fetch so I changed a little the code and added only a filter. Please check it and let me know

2022-06-17 02:58 UTC, IvanHGo commented on src/Components/SuperAdmins/index.jsx
> +  const isLoading = useSelector((state) => state.superAdmins.isLoading);
Added! thanks!

2022-06-19 21:12 UTC, AnaMurinigo commented
Test Result: Pass
GREAT work

2022-06-20 00:59 UTC, Agustin-Chazarreta approved these changes

2022-06-20 01:01 UTC, merged