BaSP-TG-76: Time sheet redux implementation
BaSP-m2022/diego-trackgenix-app pull request #38
Opened 2022-06-14 22:14 UTC by Agustin-Chazarreta

2022-06-16 16:11 UTC, cellamarematias commented on src/Components/TimeSheets/index.jsx
>      fetch(`${process.env.REACT_APP_API_URL}/projects/`)
Hi, this fetch should be in thunk.js.

2022-06-16 16:14 UTC, cellamarematias requested changes

2022-06-16 16:14 UTC, cellamarematias commented on src/Components/TimeSheets/index.jsx
> +          fetchTimeSheets={() => getTimeSheets()(dispatch)}
Hi, this fetch should be in thunk.js.

2022-06-17 02:05 UTC, Agustin-Chazarreta commented on src/Components/TimeSheets/index.jsx
>      fetch(`${process.env.REACT_APP_API_URL}/projects/`)
to do this i need all the thunks of the others entities, it just a patch implementation.

2022-06-17 02:13 UTC, cellamarematias commented on src/Components/TimeSheets/index.jsx
>      fetch(`${process.env.REACT_APP_API_URL}/projects/`)
I get it!

2022-06-17 02:14 UTC, cellamarematias approved these changes

2022-06-18 16:55 UTC, AnaMurinigo approved these changes
Test Result: Pass

2022-06-20 17:56 UTC, merged